[package]
name = "elf"
version = "0.1.0"
authors = ["WhiteGrouse <39170892+WhiteGrouse@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byteorder = "1.3.4"
